-- =====================================================
-- 1️⃣ DANH MỤC NODE
-- =====================================================
CREATE TABLE devices (
    node_id TEXT PRIMARY KEY,                     -- ID duy nhất của node (VD: NODE_01)
    node_name TEXT NOT NULL,                      -- Tên hiển thị
    owner TEXT,                                   -- Chủ sở hữu
    location TEXT,                                -- Vị trí
    created_at TIMESTAMPTZ DEFAULT NOW()          -- Thời điểm tạo
);

-- =====================================================
-- 2️⃣ TRẠNG THÁI HIỆN TẠI NODE
-- =====================================================
CREATE TABLE node_status (
    node_id TEXT PRIMARY KEY REFERENCES devices(node_id) ON DELETE CASCADE,
    current_status TEXT NOT NULL DEFAULT 'ONLINE', -- ONLINE / OFFLINE / ERROR
    previous_status TEXT,                          -- Trạng thái trước đó
    rssi INTEGER,                                  -- RSSI hiện tại (dBm)
    up_time_sec BIGINT DEFAULT 0,                  -- Uptime firmware gửi (giây)
    last_changed TIMESTAMPTZ DEFAULT NOW(),        -- Bắt đầu trạng thái hiện tại
    updated_at TIMESTAMPTZ DEFAULT NOW()           -- Cập nhật gần nhất
);

-- =====================================================
-- 3️⃣ LỊCH SỬ TRẠNG THÁI NODE
-- =====================================================
CREATE TABLE node_status_history (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    node_id TEXT REFERENCES devices(node_id) ON DELETE CASCADE,
    status TEXT NOT NULL,                           -- ONLINE / OFFLINE / ERROR
    rssi INTEGER,                                   -- RSSI tại thời điểm chuyển trạng thái
    up_time_sec BIGINT,                             -- Uptime tại thời điểm đó
    started_at TIMESTAMPTZ NOT NULL,                -- Bắt đầu trạng thái
    ended_at TIMESTAMPTZ,                           -- Kết thúc (NULL nếu đang active)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_node_status_history_node_time
ON node_status_history(node_id, started_at DESC);

-- =====================================================
-- 4️⃣ TRẠNG THÁI HIỆN TẠI THIẾT BỊ
-- =====================================================
CREATE TABLE device_status (
    component_id TEXT PRIMARY KEY,                 -- VD: NODE_01_PUMP_01
    node_id TEXT REFERENCES devices(node_id) ON DELETE CASCADE,
    component_type TEXT,                           -- PUMP / FAN / LIGHT
    current_status TEXT NOT NULL DEFAULT 'OFF',    -- ON / OFF / ERROR
    previous_status TEXT,                          -- Trạng thái trước
    trigger_source TEXT,                           -- SENSOR / CLOUD / TIMER
    last_changed TIMESTAMPTZ DEFAULT NOW(),        -- Bắt đầu trạng thái hiện tại
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- 5️⃣ LỊCH SỬ BẬT/TẮT THIẾT BỊ 
-- =====================================================
CREATE TABLE device_status_history (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    component_id TEXT REFERENCES device_status(component_id) ON DELETE CASCADE,
    node_id TEXT REFERENCES devices(node_id),
    status TEXT NOT NULL,                          -- ON / OFF
    trigger_source TEXT,                           -- Ai kích hoạt
    current_consumption FLOAT,                     -- Dòng điện tại thời điểm đó (Ampere)
    flow_rate FLOAT,                               -- Lưu lượng nước (L/phút)
    started_at TIMESTAMPTZ NOT NULL,               -- Bắt đầu
    ended_at TIMESTAMPTZ,                          -- Kết thúc
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_device_status_history_component_time
ON device_status_history(component_id, started_at DESC);

-- =====================================================
-- 6️⃣ DỮ LIỆU CẢM BIẾN (TIME-SERIES)
-- =====================================================
CREATE TABLE measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id TEXT REFERENCES devices(node_id) ON DELETE CASCADE,
    temp FLOAT,                                    -- Nhiệt độ (°C)
    humi FLOAT,                                    -- Độ ẩm không khí (%)
    soil FLOAT,                                    -- Độ ẩm đất (%)
    light FLOAT,                                   -- Cường độ ánh sáng
    created_at TIMESTAMPTZ NOT NULL                -- Thời gian Gateway (UTC)
);

CREATE INDEX idx_measurements_node_time
ON measurements(node_id, created_at DESC);

-- =====================================================
-- 7️⃣ LỊCH SỬ LỆNH ĐIỀU KHIỂN
-- =====================================================
CREATE TABLE command_history (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cmd_id TEXT,                                   -- ID lệnh
    node_id TEXT REFERENCES devices(node_id),
    component_id TEXT,                             -- Thiết bị nhận lệnh
    command TEXT,                                  -- ON / OFF
    trigger_source TEXT,                           -- CLOUD / AUTO
    success BOOLEAN,                               -- TRUE nếu ACK thành công
    error_code TEXT,                               -- Mã lỗi
    message TEXT,                                  -- Nội dung chi tiết
    executed_at TIMESTAMPTZ,                       -- Node thực thi lúc nào
    server_time TIMESTAMPTZ,                       -- Server nhận ACK lúc nào
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_command_node_time
ON command_history(node_id, created_at DESC);