-- ==========================================
-- 1. BẢNG TĨNH: DANH MỤC THIẾT BỊ
-- ==========================================
CREATE TABLE devices (
    node_id TEXT PRIMARY KEY,            -- Ví dụ: NODE_01
    node_name TEXT NOT NULL,             -- Ví dụ: Vườn Cam Khu A
    owner TEXT NOT NULL,             -- Ví dụ: Vườn Cam Khu A
    location TEXT,                       -- Ví dụ: Tọa độ hoặc vị trí tương đối
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 2. BẢNG TỨC THÌ: SỨC KHỎE NODE
-- ==========================================
CREATE TABLE node_status (
    node_id TEXT PRIMARY KEY REFERENCES devices(node_id) ON DELETE CASCADE,
    current_status TEXT NOT NULL DEFAULT 'ONLINE', -- ONLINE, OFFLINE, ERROR
    previous_status TEXT,
    rssi INTEGER,                        -- Tín hiệu LoRa (dBm)
    up_time_sec BIGINT DEFAULT 0,
    last_changed TIMESTAMPTZ DEFAULT NOW(),
    duration_minutes FLOAT DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 3. BẢNG TỨC THÌ: VẬN HÀNH THIẾT BỊ
-- ==========================================
CREATE TABLE device_status (
    component_id TEXT PRIMARY KEY,       -- Ví dụ: NODE_01_PUMP_01
    node_id TEXT REFERENCES devices(node_id) ON DELETE CASCADE,
    component_type TEXT,                 -- PUMP, FAN, LIGHT
    current_status TEXT NOT NULL DEFAULT 'OFF',
    previous_status TEXT,
    trigger_source TEXT,                 -- SENSOR, CLOUD, TIMER, LOCAL_BUTTON
    control_lock BOOLEAN DEFAULT FALSE,
    current_consumption FLOAT DEFAULT 0, -- Dòng điện (Ampe)
    flow_rate FLOAT DEFAULT 0,           -- Lưu lượng (L/phút)
    last_value FLOAT,                    -- Độ ẩm đất lúc kích hoạt
    last_changed TIMESTAMPTZ DEFAULT NOW(),
    duration_minutes FLOAT DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 4. BẢNG LỊCH SỬ: DỮ LIỆU CẢM BIẾN (BATCH)
-- ==========================================
CREATE TABLE measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id TEXT REFERENCES devices(node_id) ON DELETE CASCADE,
    temp FLOAT,
    humi FLOAT,
    soil FLOAT,
    light FLOAT,
    created_at TIMESTAMPTZ NOT NULL      -- Thời gian lấy từ Gateway (NTP)
);